---
title: "Tutorial for GWAS with SLOPE"
author: "Piotr Sobczyk"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial for GWAS with SLOPE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Clumping Procedure for SLOPE

## Running clumped SLOPE on examplary data

If you have **large dataset in files**, we recommend you load
them with **function main.R**, which will perform whole GWAS
automatically.

```{r}
library(cps)
pheFile <- system.file("extdata", "plinkPhenotypeExample.phe", package = "cps")
pheFile
snpsFile <- system.file("extdata", "plinkDataExample.raw", package = "cps")
snpsFile
main(phenotypeFile = pheFile, snpFiles = snpsFile, pValMax = 0.1)
```

#### Calling SLOPE for data pre-loaded in R

You can call SLOPE, clumping will be done automatically

```{r}
clumpedSLOPE(y, SNPs, rho = 0.3, fdr = 0.1)
```


#### Performing clumping alone

```{r, results='hide'}
clumpingResult <- clumpProcedure(cps::y, cps::SNPs)
```

```{r}
clumpingResult
```
